### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by miroslav-lalovic-devtech**
What's the purpose of this MR?
To test and evaluate Simple App - CRUD

#Impact Analysis
(N/A)

#Where should the tester start?
(N/A)

#How should this be manually tested?
Guide provided in README.md

#Any background context you want to provide?
Nothing for now.

#What are the relevant tickets?
(N/A)

#Screenshots (if appropriate)
(N/A)

### CODE REVIEW

**Comment by dejan-babic** [comment]
When you get to it, use merge request template.

**Comment by miroslav-lalovic-devtech** [comment]
@dejan-babic 
Pull request updated with a merge request template.

**Comment by dejan-babic** [comment]
1. File Structure
Not to bad, but you can make it even better with these changes
Add a namespace root (basically a folder in current source folder) like ML or Mitjo or something and have everything there e.g. source/ML/DatabaseManager like you have source/Irwin/...
Move all the database related stuff to DatabaseManager folder, so no need for crud folder anymore
Move the config file to root of repo, best practice for config files.

2. Logic/Approach
The bootsrtap.php and Database.php both deal with some logic that handles the type of database (if DATABASE = something tra la la). This is a good indicator that something is not done right. In my opinion the Database.php should not hold logic of that type. For example, good solution would be that bootstrap loads the proper handler (MySQL or Mongo) and injects that into a Main Database manager.

3. General 
PSR 2 standards and more comments.

**Comment by dejan-babic** [comment]
Not quite what I meant.
You need to separate concerns, and choose wiser naming.
Your MySQL.php is a Service for crud actions on Animals. Why is it called MySQL then? Why do you need similar one for MongoDB.php. If you want to create a Service, you only need one per model, in your case one for the Animal model you have. This means that you will need to have two handlers or helpers or what ever you want to call them, one for MySQL one for Mongo. You want to end up with something like this in bootstrap.php
```
...
if (DATABASE == 'mysql') 
{
        $animalService = new AnimalService(new MySQLHelper())
}
...
```
Please move the Databse folder/files under your namespace (Irwin)

**Comment by miroslav-lalovic-devtech** [comment]
@dejan-babic ,

Please take a look at this update and if this now suits what you meant.

Thanks!

**Comment by dejan-babic** [comment]
Bit better.
Your (for example) MySQL helper should extend the main Database class. The logic below from bootstrap.php can now live in the helper's constructor.
```
$db = new \PDO('mysql:host=' . HOST . ';dbname=' . NAME, USERNAME, PASSWORD);
$db->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
```
All the database files belong to your namespace so they should not live in a root folder called database.
Imagine if you needed to pack your solution for composer for example, and someone downloads your solution. It is a big chance they will already have a class called Database. Everything yours needs to be under src\Devtech\DatabaseManager e.g. or source\Irwin ...

**Comment by miroslav-lalovic-devtech** [comment]
I hope this is it now, Database namespace is no more, it's added to Irwin\Animal namespace, also DB connection is now happening in handlers.

**Comment by dejan-babic** [comment]
Almost there, some tweaks.
File structure - Irwin/Animalia and Irwin/Database or in the future e.g. Irwin/Logging and Irwin/Metrics.
Is `$instance = Irwin\Animal\Database::getInstance();` used anymore?
I have a problem with this function  `self::getConnection($db);` You are saying give me back what I pass in, makes no sense. Also, you have instance, and connection mixed up, you need to sort it out. Simple solution would be when you instantiate e.g. MongoDBHelper, store the $db as a property. The getConnection should return that property, so in the end you will have something like  `$this->getInstance()->getConnection()->executeQuery(...)`
You are on a good path, final fix and we are done.

**Comment by dejan-babic** [comment]
> [11-Nov-2017 00:45:52 Europe/Amsterdam] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Irwin\Animal\MongoDBHelper::getId(), 1 passed in C:\workspace\codebase\devtech\simple-app\source\Irwin\Animal\AnimalService.php on line 21 and exactly 2 expected in C:\workspace\codebase\devtech\simple-app\source\Irwin\Animal\MongoDBHelper.php:35
> Stack trace:
> #0 C:\workspace\codebase\devtech\simple-app\source\Irwin\Animal\AnimalService.php(21): Irwin\Animal\MongoDBHelper->getId('1')
> #1 C:\workspace\codebase\devtech\simple-app\public\index.php(14): Irwin\Animal\AnimalService->getOne('1')
> #2 [internal function]: {closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
> #3 C:\workspace\codebase\devtech\simple-app\vendor\klein\klein\src\Klein\Klein.php(883): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\R in C:\workspace\codebase\devtech\simple-app\vendor\klein\klein\src\Klein\Klein.php on line 954

**Comment by dejan-babic** [comment]
You still need to move the database stuff to its one namespace as mentioned.

**Pull request merged**
